name: az_travel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  app_links: ^6.1.1
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.2
  dio: ^5.4.3+1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^6.0.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.5
  form_field_validator: ^1.1.0
  get: 4.6.6
  google_sign_in: ^6.2.1
  hexcolor: ^3.0.1
  http: ^1.2.1
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  lottie: ^3.1.0
  midtrans_sdk: ^0.4.0
  permission_handler: ^11.3.0
  phosphor_flutter: ^2.0.1
  sizer: ^2.0.15
  syncfusion_flutter_datepicker: 25.1.35
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - .env
