// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwvw-oHSMeSSrrXtSg082gqh5sNcIcJME',
    appId: '1:24614197256:web:5889c3680885f802b159bd',
    messagingSenderId: '24614197256',
    projectId: 'aztravel-20616',
    authDomain: 'aztravel-20616.firebaseapp.com',
    storageBucket: 'aztravel-20616.appspot.com',
    measurementId: 'G-9PGGRZY9BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1lkm_WQv3UXSzBLYBdrk0yGzFHjCCB7o',
    appId: '1:24614197256:android:c62d328756976543b159bd',
    messagingSenderId: '24614197256',
    projectId: 'aztravel-20616',
    storageBucket: 'aztravel-20616.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5gq834wWP7oWae-3YM2d5gMlVdEZTiro',
    appId: '1:24614197256:ios:133a686fca1d54a6b159bd',
    messagingSenderId: '24614197256',
    projectId: 'aztravel-20616',
    storageBucket: 'aztravel-20616.appspot.com',
    iosClientId: '24614197256-hdmofnnhujk06i3vc88ocmkcufik8ci8.apps.googleusercontent.com',
    iosBundleId: 'com.example.azTravel',
  );
}
